### PR TITLE
fix: loco generate reqeust test template use pkg_name

### PR DESCRIPTION
**Pull request by fan-tastic-z**
fix https://github.com/loco-rs/loco/issues/132

### CODE REVIEW

**Comment by jondot** [comment]
You probably want to add `pkg_name` to the [template context](https://github.com/loco-rs/loco/blob/master/src/gen/mod.rs#L106), like done here:

https://github.com/loco-rs/loco/blob/master/src/gen/mod.rs#L111

**Comment by fan-tastic-z** [comment]
> template context

thanks,I update pr code

**Comment by jondot** [comment]
@fan-tastic-z thanks, there is one additional place here: https://github.com/loco-rs/loco/blob/master/src/gen/scaffold.rs#L52

**Comment by fan-tastic-z** [comment]
@jondot Thank you very much for your help. I just started learning Rust and found loco to be a great project. I hope I can learn Rust better through loco.

**Pull request merged**
