### PR TITLE
[WIP]: start file upload implementation

### PR DESCRIPTION
**Pull request by kaplanelad**
Enable file upload functionality with this implementation, built upon the [crate](https://github.com/kaplanelad/active-storage). It provides support for various stores, including:

Amazon S3 (was s3)
Local/in-memory (primarily for testing purposes)

The implementation includes:

1. New Hook storage: Introduces a new  Hook called storage that allows the user to configure the application stores
2. Context Integration: The store instance is now integrated into the application context, ensuring easy accessibility and utilization.
3. Example Upload Endpoint: A practical demonstration is provided by creating an upload endpoint in the demo section.

@yinho999 can you please go over it and give your feedback?

### CODE REVIEW

**Comment by yinho999** [comment]
Thanks for asking for my feedback. The hook in the library looks nice and easy to use. However I am not able to view the mentioned active-storage crate, seems like it has something to do with the visibility issue of the repository.

**Comment by kaplanelad** [comment]
i added a wong link. 
https://github.com/kaplanelad/active-storage

**Comment by yinho999** [comment]
@kaplanelad This crate is splendid! Is there issues I can contribute to this PR or your crate?

**Comment by kaplanelad** [comment]
thanks @yinho999, I'm planning to implement azure and gcp. do you want to help me with that?

**Comment by yinho999** [comment]
@kaplanelad Yes, I would like to work on that.

**Comment by fan-tastic-z** [comment]
This is my need!

**Comment by kaplanelad** [comment]
Working on new PR

**Pull request closed without merging**
