### PR TITLE
feat: add merge function to Routes

### PR DESCRIPTION
**Pull request by killix**
This pull request introduces a new merge method to the Routes struct, enabling the merging of routes with prefixes. The method efficiently combines routes from different sources, enhancing the flexibility and scalability of the routing system.

### CODE REVIEW

**Comment by kaplanelad** [comment]
Thanks, @killix! Could you please ensure that this feature is properly documented in our documentation?

**Comment by kaplanelad** [comment]
@killix can you please fix also the checks?

**Comment by killix** [comment]
> Thanks, @killix! Could you please ensure that this feature is properly documented in our documentation?

What do you mean? The documentation is not generated from the Rust comments?

> @killix can you please fix also the checks?

yes, I will take a look.

**Comment by kaplanelad** [comment]
@killix, do you have any updates?

**Pull request closed without merging**
