### PR TITLE
Fixtures use AppContext instead of DatabaseConnection

### PR DESCRIPTION
**Pull request by DenuxPlays**
# Breaking Change!!

This is a breaking change due to changing the argument of the `Hooks` trait.

# Refs

Needs: https://github.com/loco-rs/loco/pull/1061

Closes: https://github.com/loco-rs/loco/issues/1060

### CODE REVIEW

**Comment by DenuxPlays** [comment]
I think the loco-new:ci is broken

It's just looping over the same 15 Tests.

**Comment by DenuxPlays** [comment]
> I think the loco-new:ci is broken
> 
> It's just looping over the same 15 Tests.

GitHub will kill it after 6 hours which will result in a "failure".
So nothing I can do here.

**Comment by kaplanelad** [comment]
@DenuxPlays 
Could you explain the use case? Why is it necessary to include the app context within the seed hook?

**Comment by DenuxPlays** [comment]
> @DenuxPlays Could you explain the use case? Why is it necessary to include the app context within the seed hook?

As described in the issue.
Ref: https://github.com/loco-rs/loco/issues/1060#issuecomment-2536214090

**Comment by DenuxPlays** [comment]
Closing it for now.
One big PR makes more sense.

Discussion here: https://github.com/loco-rs/loco/discussions/1072

**Pull request closed without merging**
