### PR TITLE
feat: nginx deployment

### PR DESCRIPTION
**Pull request by arferreira**
Implement and add to our CLI the generation of the nginx conf file for deployment as mentioned in the issue: [(https://github.com/loco-rs/loco/issues/203)]

@jondot I had some questions about whether for now we can start with the simplest implementation and wait for demand, or whether we could think about SSL and TLS. Regarding the current implementation, it is very simple looking directly at the configurations made.

### CODE REVIEW

**Comment by jondot** [comment]
Looks great! I think simplicity is a fantastic thing :)

What do you think about looking a the docker-compose https://github.com/clowzed/sero/blob/master/docker-compose.yml and trying to customize this one to our needs? then drop the generated docker-compose file in `ngnix/` as well. This will be a great "dont make me think" feature that will streamline deploying under nginx.

Only add it if its not too complicated, if you find that it involved some jumping through hoops, we can leave it to later :)

**Comment by kaplanelad** [comment]
You can also look at our docker-compose in the starters template: 
https://github.com/loco-rs/loco/blob/master/starters/saas/.devcontainer/docker-compose.yml

**Comment by thomas9911** [comment]
Not to be annoying, I know that nginx is the default for this problem. But maybe it would be nice to add traefik, it integrates nicely with docker-compose (adding a couple of labels) and you can get lets encrypt certificates set up quite easily.

**Comment by tjyang** [comment]
Hi
To learn more about this PR, I did a manual patching in my forked repository. 
I found there is file missed. Please review and confirm.

- deployment_nginx_config.t is missed in templates dir
image
- content of deployment_nginx_config.t
```
to: "Nginx.toml"
skip_exists: true
message: "Nginx.toml file created successfully"
---
name = "{{pkg_name}}"
```
- testing output
image

**Comment by jondot** [comment]
going to move forward with this one

**Pull request merged**
