### PR TITLE
feat(cli): pretty-print cargo loco routes

### PR DESCRIPTION
**Pull request by AngelOnFira**
This add cleaner formatting to the `cargo loco routes` command.

image

### CODE REVIEW

**Comment by kaplanelad** [comment]
Thank you, @AngelOnFira, for this PR!

We aim to minimize the number of external crates to reduce the binary size and compilation time.

If you can think of an alternative implementation that doesn’t rely on an external crate, that would be fantastic. Looking forward to your thoughts!

**Comment by AngelOnFira** [comment]
Thanks for the quick reply! I mainly wanted to just give this a test first with the dependency, but I can definitely slim it down to not use anything external. I'll ping you once I get that in order! :)

**Comment by AngelOnFira** [comment]
Here is a simple improvement:

```
METHOD URI
------ ---
GET    /_health
GET    /_ping
POST   /auth/forgot
POST   /auth/login
POST   /auth/register
POST   /auth/reset
POST   /auth/verify
GET    /cache
GET    /cache/get_or_insert
POST   /cache/insert
GET    /mylayer/admin
GET    /mylayer/echo
GET    /mylayer/user
GET    /mysession
GET    /notes
POST   /notes
GET    /notes/:id
DELETE /notes/:id
POST   /notes/:id
GET    /response/album
GET    /response/empty
GET    /response/empty_json
GET    /response/etag
GET    /response/html
GET    /response/json
GET    /response/redirect
GET    /response/render_with_status_code
GET    /response/set_cookie
GET    /response/text
POST   /upload/file
POST   /user/convert/admin
POST   /user/convert/user
GET    /user/current
GET    /user/current_api_key
GET    /view-engine/hello
GET    /view-engine/home
GET    /view-engine/simple
```
But I'm curious if a view like this might be a bit more natural to read:
```
/_health
  ├─ GET    
/_ping
  ├─ GET    
/auth
  ├─ POST   /forgot
  ├─ POST   /login
  ├─ POST   /register
  ├─ POST   /reset
  ├─ POST   /verify
/cache
  ├─ GET    
  ├─ GET    /get_or_insert
  ├─ POST   /insert
/mylayer
  ├─ GET    /admin
  ├─ GET    /echo
  ├─ GET    /user
/mysession
  ├─ GET    
/notes
  ├─ GET    
  ├─ POST   
  ├─ GET    /:id
  ├─ DELETE /:id
  ├─ POST   /:id
/response
  ├─ GET    /album
  ├─ GET    /empty
  ├─ GET    /empty_json
  ├─ GET    /etag
  ├─ GET    /html
  ├─ GET    /json
  ├─ GET    /redirect
  ├─ GET    /render_with_status_code
  ├─ GET    /set_cookie
  ├─ GET    /text
/upload
  ├─ POST   /file
/user
  ├─ POST   /convert/admin
  ├─ POST   /convert/user
  ├─ GET    /current
  ├─ GET    /current_api_key
/view-engine
  ├─ GET    /hello
  ├─ GET    /home
  ├─ GET    /simple
```
I'm going to do an iteration on that to make it a bit more clear, and maybe add some colour.

**Comment by AngelOnFira** [comment]
Alright, I think I'm happy with this version

image

I think ordering could be discussed if it's not the best, since seeing GET, POST, GET, POST, DELETE might seem out of order, but it's due to it being the same endpoint used by multiple request types. I tried to separate that visually as well as I could.

image

**Comment by AngelOnFira** [comment]
This should be ready now @kaplanelad! 🦀

**Comment by jondot** [comment]
@AngelOnFira this is beautiful, thanks!

**Comment by kaplanelad** [comment]
Thanks, @AngelOnFira, it looks much **better**! The event from the table is also great! :)

Could you please take a look at my comment and also address the CI issue?

By the way, we have a few more commands (beyond prints) that could benefit from a design update:
* **Scheduler:** cargo loco scheduler --list
* **Tasks:** cargo loco task
For testing, head over to examples/demo and run the following command.

We’d really appreciate it if you could open another PR (no need in this PR) to apply your magic to these as well!

**Comment by kaplanelad** [comment]
@AngelOnFira 
replace this color costs:
```
const RESET: &str = "\x1b[0m";
const BOLD: &str = "\x1b[1m";
const GREEN: &str = "\x1b[32m";
const BLUE: &str = "\x1b[34m";
const YELLOW: &str = "\x1b[33m";
const MAGENTA: &str = "\x1b[35m";
const RED: &str = "\x1b[31m";
```

and use [colored](https://docs.rs/colored/latest/colored/) this is exists in [cargo.toml](https://github.com/loco-rs/loco/blob/master/Cargo.toml#L57)


Thanks

**Comment by AngelOnFira** [comment]
Ah yes, that makes a lot of sense. That should be fixed now! 🙌🏻

**Comment by AngelOnFira** [comment]
I'll get CI working now

**Comment by AngelOnFira** [comment]
I was testing CI locally on my fork, and it looks like everything should pass now 🎉 I was having some issues with Mac, and temp directories, so I'll upstream some test fixes in another PR hopefully.

**Comment by jondot** [comment]
beautiful! merging!

**Pull request merged**
