### PR TITLE
starters: 0.12.0 updates (remove notes, devcontainer, prefix + more)

### PR DESCRIPTION
**Pull request by jondot**
* [ ] clean up docs (where 'notes' is mentioned)
* [ ] create a devcontainer repo with a README, like this: [https://github.com/theomessin/laravel-devcontainer](https://github.com/theomessin/laravel-devcontainer)

### CODE REVIEW

**Comment by jondot** [comment]
fixes https://github.com/loco-rs/loco/issues/820

**Comment by darricheng** [comment]
@jondot Looking at the changes, it looks like you are completely changing the saas starter template to be a clean template instead. I'm wondering if there is value in creating two saas templates:

- Demo app similar to the existing one
- Skeleton project which is the demo app without the example routes (which in this case is notes)

This way, we can serve both new users who want something to explore as well as existing users who just need a plain skeleton to start. One example of an existing well-known framework that has both options like so is SvelteKit:

Screenshot 2024-10-19 at 11 26 12 AM

**Comment by ephbaum** [comment]
question: why remove the containers?

**Comment by jondot** [comment]
@ephbaum we've gotten feedback that sometimes (because of how VSCode works) a pop up jumps in, people click "accept" and then a container workflow starts and from there confusion starts. we're going to introduce this back as a `loco g deployment` and name it something like `vscode-devcontainers` and not have it by default.

@darricheng we've gotten requests to remove the "boilerplate" because as people adopt Loco, they anyways start cleaning that up. That, combined with the ability to generate full scaffold now, makes the sample `notes` obsolete. You can now generate it back with `cargo loco g scaffold ...`

**Comment by darricheng** [comment]
@jondot I think what you said makes a lot of sense. A full-featured example like a working todo app would definitely be much better for the desired outcome of letting users explore a working app than just having a skeleton with a notes scaffold added to it.

**Comment by chamons** [comment]
Just checking out loco for a side project and I ran into this PR and wanted to note my approval.

The first thing I did was start ripping out the notes model.

**Comment by jondot** [comment]
devcontainer now here: https://github.com/loco-rs/loco-devcontainer

**Pull request merged**
