### PR TITLE
Added float support in model generation

### PR DESCRIPTION
**Pull request by shuvroroy**
Issue: #307

### CODE REVIEW

**Comment by futuretim** [comment]
Should we just go ahead and add double at the same time?

**Comment by shuvroroy** [comment]
> Should we just go ahead and add double at the same time?

Waiting @kaplanelad review. If you approves then I will add

**Comment by slyons** [comment]
I believe the original issue also mentioned `Date`

**Comment by enieber** [comment]
nice job @shuvroroy...

**Comment by enieber** [comment]
@slyons to add Date can be in another PR

**Review by kaplanelad — APPROVED** [review]
Thanks @shuvroroy

**Pull request merged**
