### PR TITLE
Add CC and BCC field to the mailers.

### PR DESCRIPTION
**Pull request by BWStearns**
Add a bcc field to Emails for the mailers.

### CODE REVIEW

**Comment by BWStearns** [comment]
I haven't tested it end to end yet. Will comment when I have. Other than the existing email test in `email_sender` is there another place it should be tested in code?

**Comment by BWStearns** [comment]
Unfortunately sendgrid [removed bcc](https://www.twilio.com/docs/sendgrid/ui/account-and-settings/mail#bcc) so I don't have a convenient way to test this end to end at the moment.

**Comment by jondot** [comment]
Looks good. Should we also add cc for completeness?

PS I like using mailtutan (written in rust) or mailhog for development. It’s really nice.

**Comment by BWStearns** [comment]
It at least doesn't error but I'm getting this in mailtutan:

```
[
    {
        "id": 1,
        "sender": "Someone contact@nativi.sh",
        "recipients": [
            "brianstestemail@gmail.com"
        ],
        "subject": "Welcome brian\n",
        "created_at": "2024-06-04 23:30:32",
        "attachments": [],
        "formats": [
            "source",
            "html",
            "plain"
        ]
    }
]
```

A quick search of their codebase says there's no cc or bcc in their codebase. Are these headers just not supported in mailtutan?

**Comment by BWStearns** [comment]
image

Ok so CC works. I'm not seeing the bcc header but it looks like mailhog doesn't support it either. I think this looks good?

**Comment by jondot** [comment]
yea lets go for it, thanks!

**Pull request merged**
