### PR TITLE
fix: delete Cargo.lock and update gitignore

### PR DESCRIPTION
**Pull request by fan-tastic-z**
fix: https://github.com/loco-rs/loco/issues/140
delete all Cargo.lock and update .gitignore

### CODE REVIEW

**Comment by kaplanelad** [comment]
@fan-tastic-z,
please note that we can't remove all the lock files.
for example loco-cli is a cli tool that needs the lock file

**Comment by fan-tastic-z** [comment]
> @fan-tastic-z, please note that we can't remove all the lock files. for example loco-cli is a cli tool that needs the lock file

ok

**Comment by fan-tastic-z** [comment]
> @fan-tastic-z, please note that we can't remove all the lock files. for example loco-cli is a cli tool that needs the lock file

can I delete xtask lock file ?

**Comment by kaplanelad** [comment]
no, this is internal cli

**Comment by fan-tastic-z** [comment]
@kaplanelad  I update pr code, Please check if it is correct

**Comment by kaplanelad** [comment]
Thank you, @fan-tastic-z, for your valuable contribution! The demo example is also necessary Cargo.lock file (CLI app).

I noticed a conflict in your pull request. I have already removed the root Cargo.lock.

Thanks once again!

**Comment by fan-tastic-z** [comment]
> Thank you, @fan-tastic-z, for your valuable contribution! The demo example is also necessary Cargo.lock file (CLI app).
> 
> I noticed a conflict in your pull request. I have already removed the root Cargo.lock.
> 
> Thanks once again!
ok! thanks

**Pull request closed without merging**
