### PR TITLE
adding file upload

### PR DESCRIPTION
**Pull request by kaplanelad**
I am currently integrating file upload support into the framework. This enhancement incorporates strategic implementations inspired by the [Ruby Active Storage](https://guides.rubyonrails.org/active_storage_overview.html:

Out-of-the-box strategies:

**Single**: Designed for working exclusively with a single storage.
**Mirror**: Enables data mirroring across multiple stores, ensuring redundancy during file downloads.
**Backup**: Facilitates file backup across multiple storage locations.

Each strategy is implemented as a trait, empowering users to create their own custom strategies based on their specific needs.

### CODE REVIEW

**Comment by kaplanelad** [comment]
@yinho999, this pull request combines your [PR](https://github.com/loco-rs/loco/pull/406) with my previous version. Thank you for the time you invested. 

Let me know what you think

**Comment by yinho999** [comment]
@kaplanelad LGTM! Thanks for your hard work as well!

**Comment by yinho999** [comment]
@kaplanelad Should we add documentation for storage features and mention each StorageBuilder setup from the objectstore crate? The configuration part might be confusing for some devs since the object_storage configuration is not within the config/*.yaml. 🤔

**Comment by kaplanelad** [comment]
@yinho999  yes sure, 
I have some fixes that i want to do and then i'll add documentation. keep it to the end

**Comment by kaplanelad** [comment]
@yinho999, I've included a documentation section. Could you please review it and share your feedback?

**Comment by yinho999** [comment]
> @yinho999, I've included a documentation section. Could you please review it and share your feedback?

Totally detailed about the feature. LGTM!👍

**Pull request merged**
