### PR TITLE
feat: update docs site models and fix generate model schema data type…

### PR DESCRIPTION
**Pull request by fan-tastic-z**
# What's changed and what's your intention?

https://github.com/loco-rs/loco/issues/455
Fix `cargo loco generate model` bug caused by upgrading SeaORM

I'm not sure, if I need to handle all supported types in `sea_orm_migration::schema`, so only make changes to the types previously supported by loco.
Regarding the adjustment of uuid, I am not sure whether I fixed it correctly. In order to keep it consistent with other field types, change it to:

```
uuid-> uuid_null
uuid!->uuid
uuid^->uuid_uniq
```

# Checklist

- [ ]  docs site models 
- [ ]  update `src/gen/model.rs` TYPEMAP ,Contains uuid, boolean, jsonb

### CODE REVIEW

**Comment by kaplanelad** [comment]
Thanks @fan-tastic-z for this PR. 

I think we need to improve our test coverage in this section to avoid this problem from happening again. let me prepare a PR of that and we will merge it into your PR.

**Comment by fan-tastic-z** [comment]
> Thanks @fan-tastic-z for this PR.
> 
> I think we need to improve our test coverage in this section to avoid this problem from happening again. let me prepare a PR of that and we will merge it into your PR.

Ok

**Comment by kaplanelad** [comment]
Hey @fan-tastic-z 

See this [PR](https://github.com/loco-rs/loco/pull/459); I have added a matrix with all out type options and checked to see if Loco can compiled (meaning the migration is correct). you can see the results [here](https://github.com/loco-rs/loco/actions/runs/8016009854/job/21897144020?pr=459).

We can improve it automatically from the hashmap, but for now, I think it is good. 

Can you direct your PR to me, and validate that all the fields are valid?

**Comment by fan-tastic-z** [comment]
@kaplanelad  Do you need me to merge my PR into your PR?

**Comment by kaplanelad** [comment]
You can pull from my and open your PR to this to make sure that all generator are pass

**Comment by fan-tastic-z** [comment]
@kaplanelad  
I submitted a new commit. I am not sure whether the fix on decimal_len is correct. I have now added a judgment in the template.

**Review by kaplanelad — APPROVED** [review]

**Pull request merged**
