### PR TITLE
Updated validator to `0.19`

### PR DESCRIPTION
**Pull request by DenuxPlays**
Updated validator to `0.19` and all `Cargo.lock` files where needed.

Closes: https://github.com/loco-rs/loco/issues/992

### CODE REVIEW

**Comment by jondot** [comment]
@DenuxPlays thanks for this!
Can you please update in here instead? https://github.com/loco-rs/loco/tree/master/loco-new/base_template 

this is the new way starters are made

**Comment by DenuxPlays** [comment]
> @DenuxPlays yes, revet the starters to the new path

Done!

Reverted old changes and updated the base template.

**Comment by DenuxPlays** [comment]
@kaplanelad I am also working on a pr to update all outdated dependencies.

Is this something you would accept?

**Comment by kaplanelad** [comment]
Hey @DenuxPlays,
Thank you for your willingness to contribute! 
Updating dependencies is indeed a good practice to keep the project secure and up-to-date.

However, when proposing updates, there are a few key considerations to keep in mind:

1. **Package size**: Ensure that the size increase (if any) is reasonable and won't negatively impact performance.
2. **Changelog and breaking changes:** Review the changelogs for any breaking changes or important updates that might require adjustments in the codebase.
3. **Feature flags:** Check if any new feature flags have been added or enabled by default, and verify whether they align with the project's current requirements.

We carefully choose our dependencies to maintain a balance between functionality, performance, and maintainability. To help with the review process, it would be great if your PR includes:

A summary of the changes introduced by the updated dependencies.
Any potential impact these updates might have on the project.

**Comment by DenuxPlays** [comment]
Hey @kaplanelad 

Package size and performance is not affected by this update.

The validator crate hasn't change lot of things.
I think the main "breaking" change was the bump of the msrv to 1.81
Full changelog can be found here:
https://github.com/Keats/validator/blob/master/CHANGELOG.md#0190-20241103

It's just a very basic dependecy update.

Also I have noticed a few outdated dependencies.
Have you considered using a bot like renovate or dependabot to automate this process?

**Comment by DenuxPlays** [comment]
Hopefully fixed all tests 👍

**Comment by DenuxPlays** [comment]
@kaplanelad 
CI Failures are unrelated to my change.
Should I fix them?

**Review by kaplanelad — APPROVED** [review]

**Pull request merged**
