### PR TITLE
fix: update register api log

### PR DESCRIPTION
**Pull request by fan-tastic-z**
saas and rest-api auth register fail , use `tracing::error!`

### CODE REVIEW

**Comment by kaplanelad** [comment]
@fan-tastic-z This is not something you want to be tagged as an error.
Let's say that this error shipped into your logging system. and you have users that log in with the wrong user/pass.

which action do you need to take?

**Comment by fan-tastic-z** [comment]
> @fan-tastic-z, tagged as an error in this situation, does not look like something we want to see as an error. Imagine this error entering your logging system and users attempting to log in with incorrect credentials.
> 
> What course of action would you be going to do?

@kaplanelad When I use loco to develop, I call the interface for registered users. When the registration fails, the interface returns no error message, but the log shows info. Is it better to use error? Easier to troubleshoot where the problem is

**Comment by fan-tastic-z** [comment]
> @fan-tastic-z, tagged as an error in this situation, does not look like something we want to see as an error. Imagine this error entering your logging system and users attempting to log in with incorrect credentials.
> 
> What course of action would you be going to do?

image

Regardless of whether the registration is successful or failed, the return of the interface is like this

**Comment by kaplanelad** [comment]
@fan-tastic-z, the resignation function currently invokes `create_with_password`, which, in turn, returns an error also if the user already exists. 
in this case, this is not a real error that you have something todo (and you don't want to return an error for a security reason). 

The code is present in the starter templates, allowing users the flexibility to modify and handle according to their preferences. Currently, the login is set to log information as per the design.

**Comment by fan-tastic-z** [comment]
> @fan-tastic-z, the resignation function currently invokes `create_with_password`, which, in turn, returns an error also if the user already exists. in this case, this is not a real error that you have something todo (and you don't want to return an error for a security reason).
> 
> The code is present in the starter templates, allowing users the flexibility to modify and handle according to their preferences. Currently, the login is set to log information as per the design.

@kaplanelad Got it, thank you for your answer

**Pull request closed without merging**
