### PR TITLE
fix saas ci

### PR DESCRIPTION
**Pull request by kun1988**
Saas ci lost frontend build steps. 
New project push on github repository, Actions workflow be failure.

### CODE REVIEW

**Comment by kaplanelad** [comment]
@kun1988 
The [starters](https://github.com/loco-rs/loco/tree/master/starters) directory is not the correct location for this. The template you’re referring to was originally part of the old loco-cli.

We’ve relocated the template to the [base_template](https://github.com/loco-rs/loco/blob/master/loco-new/base_template/.github/workflows/ci.yaml) path.

Note:
When implementing this, ensure that you:

* Convert ci.yaml into a template.
* Include the setup node steps only if the asset is a frontend.

If you need help let me know

**Comment by kun1988** [comment]
@kaplanelad ok, already fix base_template. Please review.

**Comment by kaplanelad** [comment]
> @kun1988 The [starters](https://github.com/loco-rs/loco/tree/master/starters) directory is not the correct location for this. The template you’re referring to was originally part of the old loco-cli.
> 
> We’ve relocated the template to the [base_template](https://github.com/loco-rs/loco/blob/master/loco-new/base_template/.github/workflows/ci.yaml) path.
> 
> Note: When implementing this, ensure that you:
> 
> * Convert ci.yaml into a template.
> * Include the setup node steps only if the asset is a frontend.
> 
> If you need help let me know

Refer to my notes: this step should be included only in the client template, not in all templates.
You need to:

1. Convert it into a template.
2. Add this section only if the user selects the client asset.

**Comment by kun1988** [comment]
> > @kun1988 The [starters](https://github.com/loco-rs/loco/tree/master/starters) directory is not the correct location for this. The template you’re referring to was originally part of the old loco-cli.
> > We’ve relocated the template to the [base_template](https://github.com/loco-rs/loco/blob/master/loco-new/base_template/.github/workflows/ci.yaml) path.
> > Note: When implementing this, ensure that you:
> > 
> > * Convert ci.yaml into a template.
> > * Include the setup node steps only if the asset is a frontend.
> > 
> > If you need help let me know
> 
> Refer to my notes: this step should be included only in the client template, not in all templates. You need to:
> 
> 1. Convert it into a template.
> 2. Add this section only if the user selects the client asset.

sorry, is ok now?

**Comment by kaplanelad** [comment]
Yes 
1. Revert the changes made in `starters/saas/.github/workflows/ci.yaml` and not include it as part of this PR
2. Add test cases to https://github.com/loco-rs/loco/blob/master/loco-new/tests/templates/asset.rs.
Example:
  ```rust
  #[rstest]
  fn test_github_ci_yaml(
      #[values(AssetsOption::None, AssetsOption::Serverside, AssetsOption::Clientside)]
      asset: AssetsOption,
  ) {
      let generator = run_generator(asset.clone());
    .....
  }
  ```

**Comment by kun1988** [comment]
> Yes
> 
> 1. Revert the changes made in `starters/saas/.github/workflows/ci.yaml` and not include it as part of this PR
> 2. Add test cases to https://github.com/loco-rs/loco/blob/master/loco-new/tests/templates/asset.rs.
>    Example:
> 
> ```rust
> #[rstest]
> fn test_github_ci_yaml(
>     #[values(AssetsOption::None, AssetsOption::Serverside, AssetsOption::Clientside)]
>     asset: AssetsOption,
> ) {
>     let generator = run_generator(asset.clone());
>   .....
> }
> ```
> 
> 3. and also change the copy file to template in https://github.com/loco-rs/loco/blob/master/loco-new/setup.rhai#L7

How can I run test cases?  When I run `cargo test` or `cargo insta test --review` in loco-new, tests are failed.
error info:
run generate: TemplateEngine(ErrorSystem("copy_template", Template(Error { kind: Msg("Failed to render '__tera_one_off'"), source: Some(Error { kind: Msg("Variable `env.RUST_TOOLCHAIN` not found in context while rendering '__tera_one_off'"), source: None }) })))

**Comment by kaplanelad** [comment]
You run it right. 
This error means you have a problem with the `ci.yaml.t` template

**Comment by kun1988** [comment]
> You run it right. This error means you have a problem with the `ci.yaml.t` template

It's not just this error. All tests are failed.
image
image
I try add env.RUST_TOOLCHAIN, it's still useless.

**Pull request closed without merging**
