### PR TITLE
blog: deploying rust app with terraform on aws fargate

### PR DESCRIPTION
**Pull request by arferreira**
Hey Loco team! 👋 I bring something cool to the blog – a step-by-step guide on how to deploy a Rust application (thanks to loco) on AWS Fargate using Terraform. This makes it much easier to deploy Loco on AWS with a minimally scalable infrastructure.

I was talking to @kaplanelad and maybe we could automate this process. I even implemented something here in loco-cli to generate my Terraform templates for me.

### CODE REVIEW

**Comment by jondot** [comment]
@arferreira fantastic post! from my end it is good to merge and publish -- from your side it is ok to publish?

**Comment by kaplanelad** [comment]
@arferreira thanks!!

**Comment by arferreira** [comment]
@jondot Thanks, that's okay for me.

**Comment by jondot** [comment]
@arferreira fantastic, we will publish this in the next version release!

**Pull request merged**
