### PR TITLE
Add axum-prometheus example

### PR DESCRIPTION
**Pull request by alexhumphreys**
Saw #403 and figured I'd try give it a go. Let me know if you had other ideas, or if you just want to work on this yourself.

This just adds axum-prometheus to the `demo` example, haven't done any customization options, or integration into the loco framework. Plus not sure what would be good documentation for this.

But at least it does work:

```
❯ curlie :3000/metrics
HTTP/1.1 200 OK
content-type: text/plain; charset=utf-8
content-length: 6320
date: Mon, 05 Feb 2024 09:57:27 GMT

# TYPE axum_http_requests_total counter
axum_http_requests_total{method="GET",status="200",endpoint="/dashboard/home"} 4
axum_http_requests_total{method="GET",status="200",endpoint="/metrics"} 1
axum_http_requests_total{method="GET",status="404",endpoint="/dmetrics"} 1

# TYPE axum_http_requests_pending gauge
axum_http_requests_pending{method="GET",endpoint="/"} 0
axum_http_requests_pending{method="GET",endpoint="/dmetrics"} 0
axum_http_requests_pending{method="GET",endpoint="/dashboard/home"} 0
axum_http_requests_pending{method="GET",endpoint="/metrics"} 1

# TYPE axum_http_requests_duration_seconds histogram
axum_http_requests_duration_seconds_bucket{method="GET",status="200",endpoint="/dashboard/home",le="0.005"} 4
axum_http_requests_duration_seconds_bucket{method="GET",status="200",endpoint="/dashboard/home",le="0.01"} 4
axum_http_requests_duration_seconds_bucket{method="GET",status="200",endpoint="/dashboard/home",le="0.025"} 4
<and so on>
```

### CODE REVIEW

**Review by kaplanelad — APPROVED** [review]

**Comment by kaplanelad** [comment]
Thanks @alexhumphreys

**Comment by kaplanelad** [comment]
@@alexhumphreys can you fix the CI?

**Comment by alexhumphreys** [comment]
@kaplanelad ah my bad, renamed a file and didn't rename it everywhere. Should be fixed now.

**Comment by alexhumphreys** [comment]
The test failures are interesting! So right now the results are this:
```
$ cargo run -- generate controller post && cargo build && cargo test requests::post
running 2 tests
test requests::post::can_request_root ... ok
test requests::post::can_get_echo ... FAILED
```
However, I run the tests individually they pass:
```
$ cargo run -- generate controller post && cargo build && cargo test requests::post::can_get_echo
running 1 test
test requests::post::can_get_echo ... ok
$ cargo run -- generate controller post && cargo build && cargo test requests::post::can_request_root
running 1 test
test requests::post::can_request_root ... ok
```
The error they're throwing is:
```
thread 'requests::post::can_get_echo' panicked at 'called `Result::unwrap()` on an `Err` value: FailedToSetGlobalRecorder(SetRecorderError { .. })', /Users/alex.humphreys/.asdf/installs/rust/1.72.1/registry/src/index.crates.io-6f17d22bba15001f/axum-prometheus-0.6.1/src/lib.rs:699:14
```
Which is [this `.install_recorder().unwrap`](https://github.com/Ptrskay3/axum-prometheus/blob/master/src/lib.rs#L699) in `auxm-prometheus`.

and that `SetRecorderError` could be from [this function in the `metrics` crate](https://github.com/metrics-rs/metrics/blob/f50f914d0c8f3fc3b5dc76fdc4f2d8c3e644c739/metrics/src/recorder/mod.rs#L104-L110) where the docs say:
```
/// An error is returned if a recorder has already been set.
```

Looks like [`loco_rs::testing::request`](https://github.com/loco-rs/loco/blob/a30afb061c72f8787ee13e03a9e10f77d8dbba9d/src/testing.rs#L187) that the test is relying on may initialize the app. So if you run two tests, the app initialized twice in the same process, the global metrics recorder has already been set, and so the the `FailedToSetGlobalRecorder(SetRecorderError)` error occurs.

I'm not sure if that's what's going on, but even if that is what's going on I'm not entirely sure how to fix it 😅

**Comment by kaplanelad** [comment]
@alexhumphreys i see.. 

In `initializers` hook under `AppContext` variable you can check if it in test mode don't include the prometheus initializer. 

what do you think?

**Comment by kaplanelad** [comment]
test feature is not enable when test wrote in `tests` folder. you can do it like that:
```rust
if environment == &Environment::Test {
         ...
};


```

**Comment by alexhumphreys** [comment]
Awesome, thanks @kaplanelad!

**Pull request closed without merging**
