### PR TITLE
Added ability to seed via rust code

### PR DESCRIPTION
**Pull request by DenuxPlays**
Closes: #972

# TODOs

- [x] create generate command

### CODE REVIEW

**Comment by kaplanelad** [comment]
Hey, 
What do you think about the example that I wrote you here, #1062?

Do you still think that the seeder is necessary? 

My feeling is that managing the custom seed logic can be more flexible in the `before_run` than the seeder cli command

**Comment by DenuxPlays** [comment]
> Hey, What do you think about the example that I wrote you here, #1062?
> 
> Do you still think that the seeder is necessary?
> 
> My feeling is that managing the custom seed logic can be more flexible in the `before_run` than the seeder cli command

Yeah could be a solution.
My point is that it gets kind of tedious to implement everything on my own.
Especially if other people want to use a good seeding system they would have to create their own system.

I also thought about customizing the auto-seeder with features like, env based seeding, seeding by tag etc.

**Comment by kaplanelad** [comment]
If the seeder becomes available to you, what different seed functions would you write? I'm still not seeing the need for it, and perhaps I'm missing something.

**Comment by DenuxPlays** [comment]
> If the seeder becomes available to you, what different seed functions would you write? I'm still not seeing the need for it, and perhaps I'm missing something.

Let me create a discussion and summarize my intention maybe this will clear up things.

**Comment by DenuxPlays** [comment]
@kaplanelad 
Discussion: https://github.com/loco-rs/loco/discussions/1072

**Comment by DenuxPlays** [comment]
Closing it for now.
One big PR makes more sense.

Discussion here: https://github.com/loco-rs/loco/discussions/1072

**Pull request closed without merging**
