### PR TITLE
Tower layer

### PR DESCRIPTION
**Pull request by yinho999**
- [x] Route based layer
- [x] Demo Role based auth example 
- [x] Demo Model Testing
- [x] Demo E2E Testing
- [x] Documentation for middleware with basic example and advance example which uses AppContext
- [x] Grammar Check for documentation

### CODE REVIEW

**Comment by jondot** [comment]
This roles addition is super interesting. I will review this feature shortly, thanks!

**Comment by kaplanelad** [comment]
Thanks @yinho999,
Looks very good and approved from my side. small comment, can you please add the [layer](https://github.com/loco-rs/loco/pull/554/files#diff-8b05ed9b5c95c2b604bb7d473a15f9cf97729532f081d4c1637df8b14053e0f4R137) function into the loco.rs docs?

**Review by kaplanelad — APPROVED** [review]

**Review by jondot — APPROVED** [review]

**Comment by yinho999** [comment]
> Thanks @yinho999, Looks very good and approved from my side. small comment, can you please add the [layer](https://github.com/loco-rs/loco/pull/554/files#diff-8b05ed9b5c95c2b604bb7d473a15f9cf97729532f081d4c1637df8b14053e0f4R137) function into the loco.rs docs?

No worries, I will add that in later

**Comment by yinho999** [comment]
@kaplanelad, added the source code and description of `layer` function into the middleware documentation. Would you mind double check about the changes, please?

**Comment by kaplanelad** [comment]
@yinho999 Yes, I saw it, and it is great. But I think to add it also here: https://loco.rs/docs/the-app/controller/

WDYT?

**Comment by kaplanelad** [comment]
I just mean that maybe we need to document the new `layer` function that you added in our docs website [here](https://github.com/loco-rs/loco/blob/master/docs-site/content/docs/the-app/controller.md)

**Review by kaplanelad — APPROVED** [review]

**Comment by kaplanelad** [comment]
Thanks @yinho999

**Pull request merged**
